POST {{host}}/host/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "Menu with food",
    "sections": [
        {
            "name": "Yummy",
            "description": "Starters",
            "items":[
                {
                    "name": "Fried Pickles",
                    "description": "Deep Fried pickles"
                }
            ]
        }
    ]
}